name: example
description: A project that showcases how to enable the recommended functions lints for Flutter apps, packages, and plugins.

publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"

# Add the latest version of `package:flutter_lints` as a dev_dependency. The
# lint set provided by this package is activated in the `analysis_options.yaml`
# file located next to this `pubspec.yaml` file.
dev_dependencies:
  function_linter: ^1.0.4  # Check https://pub.dev/packages/function_linter for latest version number.
